### ISSUE TITLE
Contribute this to mu4e?

### ISSUE THREAD

**Issue by phil-s** [Alexander-Miller/mu4e-column-faces#1]
This seems like a useful improvement to mu4e.  Consider contributing it to that project.

**Comment by Alexander-Miller** [comment]
That was my first thought as well, but [the issue I opened](https://github.com/djcb/mu/issues/1355#) didn't seem to go anywhere for quite a while, so I figured putting things into my own package would be the easier solution for both sides.

**Comment by phil-s** [comment]
Cool; thank you for trying, and for making the feature available regardless.
