### ISSUE TITLE
mu 1.8 update breakes this package

### ISSUE THREAD

**Issue by OlMon** [Alexander-Miller/mu4e-column-faces#6]
Hej Hej,

Thanks for this awesome package.
With today mu/mu4e update, this is not working anymore. I think in #4 it was already discussed, but then it was a mu4e WIP version.

Cheers and Thanks!

**Comment by averter** [comment]
Same here

**Comment by Alexander-Miller** [comment]
I've gotten the update now myself. Patch will drop shortly.
