### ISSUE TITLE
Flag icons getting replaced causing header misalignment 

### ISSUE THREAD

**Issue by djs42012** [Alexander-Miller/mu4e-column-faces#7]
Hello Alexander,

I am experiencing an issue where `mu4e-column-faces-mode` is replacing the default Flag icons used in Doom, and causing an offset in the headers view. I have attached a couple of photos to show the before and after.
**Before:**
![2022-11-10-143508_266x171_scrot](https://user-images.githubusercontent.com/93899859/201190276-cadb79e9-8954-4e0d-8dde-b5264f6de084.png)
**After:**
![2022-11-10-143450_278x176_scrot](https://user-images.githubusercontent.com/93899859/201190279-ef0687f0-6013-437f-a4b9-3c7216bf3324.png)
I took a look through the code but couldn't identify what would cause this. I also tried providing override advice to `mu4e-column-faces--determine-face` to leave out the flagged column altogether, but couldn't figure out how to advice a function defined with `define-inline`. 

I would very much like to use the package, but only if I can get this minor detail sorted. I am running the latest release of Doom, and as far as I know do not have any special configuration applied that should be affecting iconsets.

Please let me know if there is anything I can provide that would be helpful in debugging this?

Thank you!

**Comment by Alexander-Miller** [comment]
> I would very much like to use the package, but only if I can get this minor detail sorted.

One option you have is to disable these chars via `mu4e-use-fancy-chars`. Or you can use different symbols - I can't reproduce the problem locally with mu's defaults, so there's likely something weird going on with your fonts. 

> Please let me know if there is anything I can provide that would be helpful in debugging this?

What are the values of all of your `mu4e-headers-***-mark` variables?

> I also tried providing override advice to mu4e-column-faces--determine-face to leave out the flagged column altogether, but couldn't figure out how to advice a function defined with define-inline.

You can't. That's the disadvantage of inlining. The only thing you can do is make your changes right in the code and recompile.
